// Sem4/web/lab-7-monashah0996/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class Tasklist {
  tasklist: any = [
    {
      title: 'Humber',
      tasks: ['Task 1', 'Task 2', 'Task 3'],
      id: 1,
    },
    {
      title: 'MERN',
      tasks: ['Lab', 'Project', 'Quiz'],
      id: 2,
    },
    {
      title: 'Java',
      tasks: ['Group Discussion', 'Exam', 'Assignment'],
      id: 3,
    },
  ];
  searchTasklist(title: HTMLInputElement) {
    if (title.value != '') {
      this.tasklist = this.tasklist.filter((task: any) =>
        task.title.toLowerCase().includes(title.value.toLowerCase())
      );
    } else {
      this.tasklist = [
        {
          title: 'Humber',
          tasks: ['Task 1', 'Task 2', 'Task 3'],
          id: 1,
        },
        {
          title: 'MERN',
          tasks: ['Lab', 'Project', 'Quiz'],
          id: 2,
        },
        {
          title: 'Java',
          tasks: ['Group Discussion', 'Exam', 'Assignment'],
          id: 3,
        },
      ];
    }
  }

  deleteTasklist(id: number) {
    this.tasklist.forEach((element: any, index: any) => {
      if (element.id == id) this.tasklist.splice(index, 1);
    });
  }
}

// Sem4/web/lab2/src/App.tsx
import { useState } from 'react';
import Header from './components/Header';
import Task from './components/Task';
import React from 'react';
import logo from './logo.svg';
import './App.css';
import { title } from 'process';


const App = () => {
  const [tasklist, setTasklist] = useState([
  {
      title: 'Humber',
      tasks: ['Task 1', 'Task 2', 'Task 3'],
      id: 1,
  },
  {
      title: 'MERN',
      tasks: ['Lab', 'Project', 'Quiz'],
      id: 2,
  },
  {
      title: 'Java',
      tasks: ['Group Discussion', 'Exam', 'Assignment'],
      id: 3,
  },
]);
  return (
    <div>
        <Header title='Task Lists' totalItems={9} />
        {tasklist.map((t) => {
          const{title,tasks,id} = t;
          return(
            <Task title={title} tasks={tasks} key={id.toString()} />
          );
          
        })}
      </div>
  );
};
export default App;
